name: misc
channels:
  - pytorch
  - anaconda
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h7f8727e_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py38h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotli=1.0.9=he6710b0_2
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi=2022.5.18.1=py38h06a4308_0
  - cffi=1.15.0=py38hd667e15_1
  - cudatoolkit=11.1.74=h6bb024c_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38h06a4308_0
  - expat=2.4.4=h295c915_0
  - ffmpeg=4.2.2=h20bf706_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.4.1=py38h06a4308_1
  - ipython=7.31.1=py38h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py38h06a4308_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=4.4.0=py38h06a4308_0
  - jupyter=1.0.0=py38_7
  - jupyter_client=7.2.2=py38h06a4308_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=4.10.0=py38h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.4.2=py38h295c915_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.2=h7f8727e_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.14=h74e7548_0
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.1.1=py38h7f8727e_0
  - matplotlib=3.4.2=py38h06a4308_0
  - matplotlib-base=3.4.2=py38hab158f2_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - munkres=1.1.4=py_0
  - nbclient=0.5.13=py38h06a4308_0
  - nbconvert=6.4.4=py38h06a4308_0
  - nbformat=5.3.0=py38h06a4308_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.5=py38h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - notebook=6.4.11=py38h06a4308_0
  - numpy=1.22.3=py38he7a7128_0
  - numpy-base=1.22.3=py38hf524024_0
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1o=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - patchelf=0.12=h2531618_1
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.4=py38h06a4308_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.18.0=py38heee7806_0
  - python=3.8.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - pytorch=1.9.0=py3.8_cuda11.1_cudnn8.0.5_0
  - pyzmq=22.3.0=py38h295c915_2
  - qt=5.9.7=h5867ecd_1
  - qtconsole=5.3.0=pyhd3eb1b0_0
  - qtpy=2.0.1=pyhd3eb1b0_0
  - readline=8.1.2=h7f8727e_1
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=61.2.0=py38h06a4308_0
  - sip=4.19.13=py38h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.38.3=hc218d9a_0
  - terminado=0.13.1=py38h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.9.0=py38
  - torchvision=0.10.0=py38_cu111
  - tornado=6.1=py38h27cfd23_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py38h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.5=h7f8727e_1
  - zeromq=4.3.4=h2531618_0
  - zipp=3.8.0=py38h06a4308_0
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.4.9=haebb681_0
  - pip:
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - appdirs==1.4.4
    - async-timeout==4.0.2
    - audioread==2.1.9
    - castepxbin==0.1.0
    - cbor==1.0.0
    - charset-normalizer==2.0.9
    - click==8.1.2
    - cloudpickle==1.6.0
    - cython==0.29.24
    - datasets==2.1.0
    - dill==0.3.4
    - django==3.2.9
    - django-cors-headers==3.10.0
    - docker-pycreds==0.4.0
    - easyocr==1.4.1
    - fasteners==0.16.3
    - filelock==3.6.0
    - frozenlist==1.3.0
    - fsspec==2022.3.0
    - future==0.18.2
    - gitdb==4.0.9
    - gitpython==3.1.27
    - glfw==2.1.0
    - gym==0.19.0
    - h5py==3.6.0
    - huggingface-hub==0.5.1
    - idna==3.3
    - imageio==2.9.0
    - jiwer==2.3.0
    - joblib==1.1.0
    - librosa==0.9.1
    - llvmlite==0.38.0
    - monty==2021.12.1
    - mpmath==1.2.1
    - mujoco-py==2.1.2.14
    - multidict==6.0.2
    - multiprocess==0.70.12.2
    - networkx==2.6.3
    - numba==0.55.1
    - opencv-python-headless==4.5.4.58
    - palettable==3.3.0
    - pandas==1.4.2
    - pathtools==0.1.2
    - phonopy==2.12.0
    - pillow==8.2.0
    - plotly==5.4.0
    - pooch==1.6.0
    - promise==2.3
    - protobuf==3.19.1
    - psutil==5.9.0
    - pyarrow==8.0.0
    - pyglet==1.5.21
    - pymatgen==2022.0.16
    - pypdf==1.13
    - pypdf2==1.26.0
    - python-bidi==0.4.2
    - python-levenshtein==0.12.2
    - pytz==2021.3
    - pywavelets==1.1.1
    - pyyaml==6.0
    - regex==2022.4.24
    - requests==2.26.0
    - resampy==0.2.2
    - responses==0.18.0
    - ruamel-yaml==0.17.17
    - ruamel-yaml-clib==0.2.6
    - sacremoses==0.0.49
    - scikit-image==0.18.3
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - seekpath==2.0.1
    - sentry-sdk==1.6.0
    - setproctitle==1.2.3
    - shortuuid==1.0.9
    - smmap==5.0.0
    - soundfile==0.10.3.post1
    - spglib==1.16.2
    - sumo==2.2.5
    - sumo-rl==1.1
    - sympy==1.9
    - tabulate==0.8.9
    - tenacity==8.0.1
    - tensorboardx==2.4.1
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - tokenizers==0.12.1
    - tqdm==4.64.0
    - transformers==4.20.1
    - uncertainties==3.1.6
    - urllib3==1.26.7
    - wandb==0.12.19
    - xxhash==3.0.0
    - yarl==1.7.2
prefix: /home/thunder/anaconda3/envs/misc
